
all:
	cicpy transpile SAR9B_CV.cic.gz demo.tech SAR9B --layskill --schskill --verilog --xschem --spice --winfo --rinfo demo.txt --magic

clean:
	-rm *.spice
	-rm *.spi
	-rm *.yaml
	-rm -rf SAR9B
	-rm *.il
	-rm *.v
